// src/components/Home.jsx
import React from "react";
import Header from "./Header.jsx";
import styles from "./Home.module.css";

function Home() {

  const navigationItems = [
    {
      path: "/dex",
      title: "Dex",
      description: "Track your main Pokédex completion in Pokémon GO",
      icon: "📚",
    },
    {
      path: "/shiny",
      title: "ShinyDex",
      description: "Track which of the available shinies you've caught",
      icon: "✨",
    },
    {
      path: "/lucky",
      title: "LuckyDex",
      description: "Track how many lucky Pokémon you've acquired",
      icon: "🍀",
    },
    {
      path: "/unown",
      title: "UnownDex",
      description: "Track how many Unown you own",
      icon: "🔤",
    },
    {
      path: "/shadow",
      title: "ShadowDex",
      description: "Track how many shadow Pokémon you have",
      icon: "😈",
    },
  ];

  return (
    <div className={styles.homeContainer}>
      <Header title="GO Checklists" />

      <div className={styles.content}>
        <div className={styles.navigationGrid}>
          {navigationItems.map((item, index) => (
            <a key={index} href={item.path} className={styles.navigationCard}>
              <div className={styles.cardHeader}>
                <div className={styles.cardIcon}>{item.icon}</div>
                <h3 className={styles.cardTitle}>{item.title}</h3>
              </div>
              <p className={styles.cardDescription}>{item.description}</p>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Home;

// src/app/home/home.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "ns-home",
  moduleId: module.id,
  styleUrls: ["./home.component.css"],
  templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
  }
}

<h1><span>GO Checklists</span></h1>

<ul>
    <li>
        <a [routerLink]="['/dex']">Dex</a>
        <ul>
            <li>Track your main Pokédex completion in Pokémon GO.</li>
        </ul>
    </li>
    <li>
        <a [routerLink]="['/shiny']">ShinyDex</a>
        <ul>
            <li>Track which of the available shinies you’ve caught.</li>
        </ul>
    </li>
    <li>
        <a [routerLink]="['/lucky']">LuckyDex</a>
        <ul>
            <li>Track how many lucky Pokémon you’ve acquired.</li>
        </ul>
    </li>
    <li>
        <a [routerLink]="['/unown']">UnownDex</a>
        <ul>
            <li>Track how many Unown you own.</li>
        </ul>
    </li>
    <li>
        <a [routerLink]="['/shadow']">ShadowDex</a>
        <ul>
            <li>Track how many shadow Pokémon you have.</li>
        </ul>
    </li>
</ul>
